language: java
jdk:
  - oraclejdk8

install: ant
script: ant test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
 email:
    recipients:
      - diaz.nicolasandres@gmail.com
      - facundomastricchio@gmail.com
      - alejandroballadaresparisi@gmail.com
      - jonathangalvanperez@gmail.com

    on_failure: always
    on_success: always
